# Wrangler configuration for Cloudflare Pages
name = "piu-dapp"
compatibility_date = "2024-01-01"

# Pages configuration
[env.production]
compatibility_date = "2024-01-01"

# Environment variables for Cloudflare Pages
# These will be set in the Cloudflare dashboard
# PUBLIC_REOWN_PROJECT_ID = "your_reown_project_id"
# PUBLIC_SOLANA_RPC_URL = "https://api.mainnet-beta.solana.com"

# KV namespace bindings for session storage
[[kv_namespaces]]
binding = "SESSION"
id = "fdefca3b7c3140bc8f7d58c642cb7617"
