# Wrangler configuration for Cloudflare Pages
name = "piu-dapp"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "dist"

# KV namespace bindings for session storage
[[kv_namespaces]]
binding = "SESSION"
id = "fdefca3b7c3140bc8f7d58c642cb7617"

[env.production]
compatibility_date = "2024-01-01"
